### ISSUE TITLE
Refactoring of the navbar and tools page

### ISSUE THREAD

**Issue by Sallaa** [AFP-Medialab/verification-plugin#421]
The navigation bar and the tools reuse similar code and variables and it needs refactoring

- [x] Less error prone variables: instead of having to type the strings by hand use enums
- [x] refactor using map when possible

**Comment by ttramb** [comment]
Pre refactor have been done to NavBar and Alltools
Use one tool list 
Use fusion auth roles to filter tool and category display

**Comment by Sallaa** [comment]
We will do more refactoring in 0.83
