### ISSUE TITLE
Question regarding backend and APIs

### ISSUE THREAD

**Issue by DaryaTereshchenko** [AFP-Medialab/verification-plugin#621]
Hi!

I am a Master's student at the Department of Computational Linguistics, University of Zurich. I am currently conducting research on disinformation detection, and I have found your Google Chrome extension. Thank you for the project and your effort! As I am mainly concerned with building classifiers, I would like to ask if it is possible to use the verification plugin at the API level to pass the data I have and verify it using the plugin backend?

Thank you for any hint and reply; I appreciate your time and help!

Kind regards, 
Daria Stetsenko

**Comment by Sallaa** [comment]
Hi Daria, I assume you want to verify text. Our plugin uses APIs from Sheffield University and KInIT for text analysis. These APIs are called in the assistant and you could see some Credibility Signals directly in the Assistant. If you need API access, could you get in touch with @rosannamilner or @ianroberts? They are at Sheffield and can guide your request to the right person.

**Comment by ianroberts** [comment]
The Sheffield University tools (persuasion techniques, genre, framing and source credibility) are all publicly available as API endpoints at https://cloud.gate.ac.uk - if the standard quota is insufficient for your needs use the contact form to request an increase.  We're usually fine to grant increased quota to research users in return for a citation of GATE Cloud in any publication that comes out of the work.

**Comment by Sallaa** [comment]
@DaryaTereshchenko I am closing this issue. If you have any other question, feel free to reopen it.
