### ISSUE TITLE
language mappings Japanese localization

### ISSUE THREAD

**Issue by Sallaa** [AFP-Medialab/verification-plugin#664]
Add the Japanese localization for the list of languages in `src/LocalDictionary/semantic_search_language_mappings.json`

**Comment by Sallaa** [comment]
@nuwaa could you take care of this? I created a branch you can work on to add your changes: https://github.com/AFP-Medialab/verification-plugin/tree/664-add-the-japanese-localization-for-the-list-of-languages-in-srclocaldictionarysemantic_search_language_mappingsjson . You can then make a pull request to the `beta-master` branch. Please do not commit to the `beta-master` branch directly

**Comment by nuwaa** [comment]
@Sallaa Hello! I'll do my best to handle this while looking things up!

**Comment by nuwaa** [comment]
@Sallaa It seems that I don't have write permissions!
![image](https://github.com/user-attachments/assets/20e46218-8b07-42ff-8fcf-6b57c7553e35)

**Comment by Sallaa** [comment]
@nuwaa please do not push to beta-master but push to the branch I created for you

**Comment by nuwaa** [comment]
@Sallaa I believe I have uploaded the file with Japanese added to the specified location. Please check and confirm.

**Comment by Sallaa** [comment]
Thank you for the quick work! It looks good, I merged it 😄
