### ISSUE TITLE
Assistant tool testing

### ISSUE THREAD

**Issue by jmafoster1** [AFP-Medialab/verification-plugin#687]
I'm working on [this issue](https://github.com/GateNLP/we-verify-app-assistant/issues/225) and am struggling to test a couple of the tools. In particular:

- I can't find an image that the image analysis tool comes back successfully for. I either get "platform not supported" or "we cannot process this" or similar.
- For video rights, it seems to just hang for a long time and then come back with an "unknown error".

@Sallaa do you have any examples of media which should definitely work for these tools so that I can test that I've not broken anything please?

**Comment by jmafoster1** [comment]
@Sallaa thanks for this. Would it make sense to drop these tools out (or at least for the assistant not to recommend them to people) or should we keep it as is?

**Comment by Sallaa** [comment]
Yes, you can drop them in the assistant. We may even drop them completely at some point. I am not sure they will be maintained anymore.
